In [8]:
using Pkg

Pkg.add("FFTW")

   Resolving package versions...
  No Changes to `C:\Users\kyle\.julia\environments\v1.7\Project.toml`
  No Changes to `C:\Users\kyle\.julia\environments\v1.7\Manifest.toml`


In [1]:
function FFT(P)
   
    n=length(P)
    if n ==1
        return P
    end
   
        
    w=MathConstants.e^(-2*pi*im/n)
    P0=Vector{Complex{Float64}}()
    P1=Vector{Complex{Float64}}()
    for i in 1:n
        if i%2==0
            push!(P1,P[i])
        else
            push!(P0,P[i])
        end
    end
    y0=FFT(P0)
    y1=FFT(P1)
    y = zeros(Complex{Float64},n)
    n2 = trunc(Int,n/2)
    for j in 1:n2 
        y[j]=y0[j]+(w^(j-1))*y1[j]
        y[j+ n2]=y0[j]-(w^(j-1))*y1[j]
    end
    return y
   
end
    

FFT (generic function with 1 method)

In [2]:
using FFTW

In [3]:
p= rand(Float64, 8)
#println(im^2)
println(p)
#println(trunc(Int,10/2))

FFT(p)

[0.09686775179595675, 0.1529300239310427, 0.7956613628289222, 0.8372318558436325, 0.5551559062715336, 0.004235513028612248, 0.039140408408510186, 0.4032711093718949]


8-element Vector{ComplexF64}:
    2.884493931480105 + 0.0im
  -1.2929605052192783 + 0.3595769461156743im
   1.0833374282558723 - 0.18277811316994208im
   0.4250390122758031 + 0.062187924310813714im
 -0.08915692712974055 + 0.0im
   0.4250390122758032 - 0.06218792431081338im
   1.0833374282558723 + 0.18277811316994208im
  -1.2929605052192783 - 0.35957694611567464im

In [4]:
fft(p)

8-element Vector{ComplexF64}:
    2.884493931480105 + 0.0im
  -0.6600018440901929 - 1.1685204380036793im
 -0.18277811316994208 + 1.0833374282558723im
 -0.25657446486096064 + 0.3445214708371446im
  0.08915692712974055 + 0.0im
 -0.25657446486096064 - 0.3445214708371446im
 -0.18277811316994208 - 1.0833374282558723im
  -0.6600018440901929 + 1.1685204380036793im

In [5]:
ifft(fft(p))

8-element Vector{ComplexF64}:
  0.09686775179595675 + 0.0im
  0.15293002393104269 + 0.0im
   0.7956613628289222 + 0.0im
   0.8372318558436325 + 0.0im
   0.5551559062715336 + 0.0im
 0.004235513028612303 + 0.0im
  0.03914040840851024 + 0.0im
   0.4032711093718948 + 0.0im

In [6]:
ifft(FFT(p))

8-element Vector{ComplexF64}:
  0.40327110937189486 + 0.0im
  0.03914040840851021 - 7.850462293418876e-17im
 0.004235513028612248 + 1.3877787807814457e-17im
   0.5551559062715336 + 3.9252311467094385e-17im
   0.8372318558436325 + 0.0im
   0.7956613628289223 + 7.850462293418876e-17im
   0.1529300239310427 - 1.3877787807814457e-17im
   0.0968677517959568 - 3.9252311467094385e-17im